### ISSUE TITLE
Add .NET Standard Client SDK

### ISSUE THREAD

**Issue by Almis90** [dustout/entitysignal#3]
**Is your feature request related to a problem? Please describe.**
I would like to use it in a Xamarin project.

**Describe the solution you'd like**
I ported the JS version to C# myself, it connect successfully but the "Sync" method doesn't trigger on hub when I subscribe to it. That is my only issue (I think) can you give it a look please? Also the code will be polished afterwards but if you have any suggestion let me know.

**Describe alternatives you've considered**
If you don't like what I have done maybe you will consider creating the project yourself?

**Additional context**
Here is the link to the repository https://github.com/Almis90/entitysignal
Here is the issue, it doesn't go inside "Sync" method https://github.com/Almis90/entitysignal/blob/45e99e3ae180d6ecd1cb4277bd7e9460aece76ad/EntitySignal.Client/EntitySignalClient.cs#L68

**Comment by dustout** [comment]
Hello @Almis90 

You did a really good job of converting the client library from JS/TS to C#!

I am not sure why, but when you move the `_hub.On<UserResult>("Sync", data =>` call in the `EntitySignalClient.cs` file to the `Connect()` function right above `_hub.On<string>("ConnectionIdChanged", connectionId =>` then it will start to call the "Sync" function. I don't know enough about the c# signalr client to know why, but it does seem to fix it. I will apply my fix as a PR to your branch.

**Comment by dustout** [comment]
The link below is the version of the file where sync runs in a C# client. I have not checked to see if it works. I do like your idea of a c# client, and if you get it working please submit a PR as I would love to have this as part of the main project. 

https://github.com/dustout/entitysignal/blob/c-sharp-client/EntitySignal.Client/EntitySignalClient.cs

**Comment by Almis90** [comment]
The problem wasn't the line position, the problem was the version of Microsoft.AspNetCore.SignalR.Client, I was using 3.1.3 (which is the latest one) but I needed to use the same major version with the server (for server the latest version is 1.1.0). So now both client and server are on version 1.1.0.

I decided to bump both Client and Server to 1.1.0 instead of 1.0.0 because

1. It's the latest version
2. `_hub.Remove` was not available in version 1.0.0

**Comment by dustout** [comment]
Your code has been merged in, and a nuget package `EntitySignal.Client` has been made. Once again thank you so much for doing this @Almis90!
https://www.nuget.org/packages/EntitySignal.Client/1.0.3

Please email me at _dustout@gmail.com_ when your xamarin app launches, as I would love to check it out
