### ISSUE TITLE
[Feature] reporting feed back

### ISSUE THREAD

**Issue by davidbuckleyni** [dustout/entitysignal#6]
When in google sheets for example u can always see a user typing into a cell is this possible with asp.net core and mvc. 

Also how does one tell user a that user b is editing that record for example.

**Comment by dustout** [comment]
Hello David,

A google sheets type system should be do-able with Entity Signal. This is how I would structure the data.

### Table: DataSheet
Id | Name
------------ | -------------
1 | Test Sheet

### Table: DataSheetCell
Id | DataSheetId | Column | Row | Value
-- | ----------- | --------- | ----- | --------
1 | 1 | 1 | 1 | Test Value
2 | 1 | 1 | 2 | Test Value 2

### Table: DataSheetActiveUser
Id | DataSheetId | SelectedColumn | SelectedRow | Name | SignalRSession
-- | ----------- | --------- | ----- | -------- | --------
1 | 1 | 1 | 1 | Dustin | sdfsdfggdfg
2 | 1 | 1 | 2 | David | dfglkjdfgigg


When the user goes to the page I would then subscribe to the following patterns, and that would give the appropriate data to the front end of what is being changed and who is changing it
```
\\Subscribe to changes in the data sheet
_entitySignal.Subscribe<DataSheetCell>(x=>x.DataSheetId == 1);
```
```
\\Subscribe to who is editing the data sheet
_entitySignal.Subscribe<DataSheetActiveUser>(x=>x.DataSheetId == 1);
```

**Comment by dustout** [comment]
Also I am closing this issue since it seems more like a feature request than an issue.
